name: floating_tile_nav
description: "A floating bottom navigation bar with custom icons, controlled selection, and safe-area handling."
version: 0.1.1
repository: https://github.com/4armsxlr8/floating_tile_nav
issue_tracker: https://github.com/4armsxlr8/floating_tile_nav/issues
topics:
  - navigation
  - ui
  - widgets

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
